services:
  cassiofernando-cv:
    build: .
    image: tectonic
    container_name: cassiofernando-cv
    working_dir: "/cassiofernando-cv"
    # user: 1000:1000
    command: sh compile.sh
    volumes:
      - ./:/cassiofernando-cv
    environment:
      - XDG_CONFIG_HOME=/cassiofernando-cv/.tectonic
      - XDG_CACHE_HOME=/cassiofernando-cv/.tectonic
